import{a as f,i as c,S as g}from"./assets/vendor-DkEYWuMb.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const i of e)if(i.type==="childList")for(const l of i.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&r(l)}).observe(document,{childList:!0,subtree:!0});function s(e){const i={};return e.integrity&&(i.integrity=e.integrity),e.referrerPolicy&&(i.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?i.credentials="include":e.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function r(e){if(e.ep)return;e.ep=!0;const i=s(e);fetch(e.href,i)}})();async function d(o,a,s,r){a>0&&s>0&&(document.querySelector(".loader").classList.toggle("visually-hidden"),await f.get("https://pixabay.com/api/",{params:{key:"49309273-01bbbdbc5dd72a8afdb67bc06",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:a,per_page:s}}).then(e=>{r(e.data)}).catch(e=>{c.error({title:"Помилка!",message:e.message,position:"topRight"})}).finally(()=>{document.querySelector(".loader").classList.toggle("visually-hidden")}))}const t={searchText:"",carrentPage:1,pageLen:15,total:0};let n;function u(o){o.totalHits>t.carrentPage*t.pageLen?v():(m(),c.error({message:"We're sorry, but you've reached the end of search results.",close:!0,timeout:5e3,position:"topRight"})),h(o.hits),y()}function p(){document.querySelector(".gallery").outerHTML='<ul class="gallery"></ul>'}function h(o){if(o.length<1)c.error({message:"Sorry, there are no images matching your search query. Please try again!",close:!0,timeout:5e3,position:"topRight"});else{const a=document.createDocumentFragment(),s=document.querySelector(".gallery");for(const r of o){const e=document.createElement("li");e.classList.add("gallery-item"),e.innerHTML=`<div class="gallery-div">
        <a class="gallery-link" href="${r.largeImageURL}">
          <img class="gallery-image" src="${r.webformatURL}" alt="${r.tags}">
        </a>
      </div>
      <div class="img-footer">
        <div class="footer-item"><p>Likes</p><p>${r.likes}</p></div>
        <div class="footer-item"><p>Views</p><p>${r.views}</p></div>
        <div class="footer-item"><p>Comments</p><p>${r.comments}</p></div>
        <div class="footer-item"><p>Downloads</p><p>${r.downloads}</p></div>
      </div>`,a.appendChild(e)}s.appendChild(a)}if(t.carrentPage>1){let a=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({left:0,top:a*2,behavior:"smooth"})}}function y(){n?n.refresh():n=new g(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250,showCounter:!0,disableScroll:!0,navText:["←","→"],closeText:"×"})}function v(){document.querySelector(".load-more").classList.contains("visually-hidden")&&document.querySelector(".load-more").classList.remove("visually-hidden")}function m(){document.querySelector(".load-more").classList.contains("visually-hidden")||document.querySelector(".load-more").classList.add("visually-hidden")}document.querySelector(".form").addEventListener("submit",function(o){o.preventDefault(),m(),p(),t.searchText=o.target.elements["search-text"].value,t.carrentPage=1,t.total=0,d(t.searchText,t.carrentPage,t.pageLen,u)});document.querySelector(".load-more").addEventListener("click",function(o){t.carrentPage+=1,d(t.searchText,t.carrentPage,t.pageLen,u)});
//# sourceMappingURL=index.js.map
