import{a as p,i as c,S as g}from"./assets/vendor-DkEYWuMb.js";(function(){const i=document.createElement("link").relList;if(i&&i.supports&&i.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const l of a.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&r(l)}).observe(document,{childList:!0,subtree:!0});function s(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerPolicy&&(a.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?a.credentials="include":e.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function r(e){if(e.ep)return;e.ep=!0;const a=s(e);fetch(e.href,a)}})();async function d(t,i,s,r){i>0&&s>0&&(document.querySelector(".loader").classList.toggle("visually-hidden"),await p.get("https://pixabay.com/api/",{params:{key:"49309273-01bbbdbc5dd72a8afdb67bc06",q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:i,per_page:s}}).then(e=>{r(e.data)}).catch(e=>{c.error({title:"Помилка!",message:e.message,position:"topRight"})}).finally(()=>{document.querySelector(".loader").classList.toggle("visually-hidden")}))}const o={searchText:"",carrentPage:1,pageLen:15,total:0};let n;function u(t){t.totalHits>o.carrentPage*o.pageLen?v():(f(),c.error({message:"We're sorry, but you've reached the end of search results.",close:!0,timeout:5e3,position:"topRight"})),h(t.hits),y()}function m(){document.querySelector(".gallery").outerHTML='<ul class="gallery"></ul>'}function h(t){if(t.length<1)c.error({message:"Sorry, there are no images matching your search query. Please try again!",close:!0,timeout:5e3,position:"topRight"});else{const i=document.createDocumentFragment(),s=document.querySelector(".gallery");for(const r of t){const e=document.createElement("li");e.classList.add("gallery-item"),e.innerHTML=`<div class="gallery-div">
        <a class="gallery-link" href="${r.largeImageURL}">
          <img class="gallery-image" src="${r.webformatURL}" alt="${r.tags}">
        </a>
      </div>
      <div class="img-footer">
        <div class="footer-item"><p>Likes</p><p>${r.likes}</p></div>
        <div class="footer-item"><p>Views</p><p>${r.views}</p></div>
        <div class="footer-item"><p>Comments</p><p>${r.comments}</p></div>
        <div class="footer-item"><p>Downloads</p><p>${r.downloads}</p></div>
      </div>`,i.appendChild(e)}s.appendChild(i)}}function y(){n?n.refresh():n=new g(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250,showCounter:!0,disableScroll:!0,navText:["←","→"],closeText:"×"})}function v(){document.querySelector(".load-more").classList.contains("visually-hidden")&&document.querySelector(".load-more").classList.remove("visually-hidden")}function f(){document.querySelector(".load-more").classList.contains("visually-hidden")||document.querySelector(".load-more").classList.add("visually-hidden")}document.querySelector(".form").addEventListener("submit",function(t){t.preventDefault(),f(),m(),o.searchText=t.target.elements["search-text"].value,o.carrentPage=1,o.total=0,d(o.searchText,o.carrentPage,o.pageLen,u)});document.querySelector(".load-more").addEventListener("click",function(t){m(),o.carrentPage+=1,d(o.searchText,o.carrentPage,o.pageLen,u)});
//# sourceMappingURL=index.js.map
