import{a as d,i as f,S as u}from"./assets/vendor-DkEYWuMb.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const i of e)if(i.type==="childList")for(const s of i.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&t(s)}).observe(document,{childList:!0,subtree:!0});function r(e){const i={};return e.integrity&&(i.integrity=e.integrity),e.referrerPolicy&&(i.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?i.credentials="include":e.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function t(e){if(e.ep)return;e.ep=!0;const i=r(e);fetch(e.href,i)}})();function c(l,a,r,t){a>0&&r>0&&(document.querySelector(".loader").classList.toggle("visually-hidden"),d.get("https://pixabay.com/api/",{params:{key:"49309273-01bbbdbc5dd72a8afdb67bc06",q:l,image_type:"photo",orientation:"horizontal",safesearch:!0,page:a,per_page:r}}).then(e=>{t(e.data.hits)}).catch(e=>{console.log(e)}).finally(()=>{document.querySelector(".loader").classList.toggle("visually-hidden")}))}const o={searchText:"",carrentPage:1,pageLen:20,maxItems:60,direction:"toBottom"};let n;function m(l){p(l),y()}function g(){document.querySelector(".gallery").outerHTML='<ul class="gallery"></ul>'}function p(l){if(l.length<1)f.error({message:"Sorry, there are no images matching your search query. Please try again!",close:!0,timeout:5e3,position:"topRight"});else{const a=document.createDocumentFragment(),r=document.querySelector(".gallery");for(const t of l){const e=document.createElement("li");e.classList.add("gallery-item"),e.innerHTML=`<div class="gallery-div">
        <a class="gallery-link" href="${t.largeImageURL}">
          <img class="gallery-image" src="${t.webformatURL}" alt="${t.tags}">
        </a>
      </div>
      <div class="img-footer">
        <div class="footer-item"><p>Likes</p><p>${t.likes}</p></div>
        <div class="footer-item"><p>Views</p><p>${t.views}</p></div>
        <div class="footer-item"><p>Comments</p><p>${t.comments}</p></div>
        <div class="footer-item"><p>Downloads</p><p>${t.downloads}</p></div>
      </div>`,a.appendChild(e)}if(console.log(`Додавав ${o.direction}`),o.direction==="toBottom"){for(console.log(`To bottom ${a}`),r.appendChild(a),console.log(`Галерея after add = ${r.children.length} елементів`);r.children.length>o.maxItems;)r.removeChild(r.firstElementChild);console.log(`Gallery after del from bottom = ${r.children.length} elements`)}else if(o.direction==="toTop"){const t=r.scrollHeight;r.prepend(a);const e=r.scrollHeight;for(window.scrollBy(0,e-t);r.children.length>o.maxItems;)r.removeChild(r.lastElementChild);console.log(`Gallery after del from bottom = ${r.children.length} elements`)}}}function h(){o.runStarted=!0;const l=new IntersectionObserver((a,r)=>{const t={markerTop:!1,markerBottom:!1};a.forEach(e=>{e.isIntersecting&&(console.log(e.target.classList[1]),e.target.classList[1]==="marker-top"?t.markerTop=!0:e.target.classList[1]==="marker-bottom"&&(t.markerBottom=!0))}),t.markerBottom&&!t.markerTop?(o.direction="toBottom",c(o.searchText,++o.carrentPage,o.pageLen,m)):!t.markerBottom&&t.markerTop&&(o.direction="toTop",o.carrentPage>3&&c(o.searchText,--o.carrentPage-2,o.pageLen,m)),console.log(t),console.log(`Page = ${o.carrentPage} `)});l.observe(document.querySelector([".marker-top"])),l.observe(document.querySelector([".marker-bottom"]))}function y(){n?n.refresh():n=new u(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250,showCounter:!0,disableScroll:!0,navText:["←","→"],closeText:"×"})}h();document.querySelector(".form").addEventListener("submit",function(l){l.preventDefault(),g(),o.searchText=l.target.elements["search-text"].value,o.direction="toBottom",o.carrentPage=1,c(o.searchText,o.carrentPage,o.pageLen,m)});
//# sourceMappingURL=index.js.map
